version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1  # Using Codecov orb for CircleCI

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  # Java environment
    steps:
      - checkout  # Checkout the repository
      # Run Maven build and tests, including generating JaCoCo coverage report
      - run:
          name: Build with Tests
          command: mvn clean package
      # Generate coverage report using JaCoCo
      - run:
          name: Generate Coverage Report
          command: mvn test jacoco:report
      # Upload to Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml  # This is where JaCoCo stores the coverage report

  checkstyle:
    docker:
      - image: cimg/openjdk:11.0  # Java environment
    steps:
      - checkout  # Checkout the repository
      # Run Checkstyle to analyze code quality
      - run:
          name: Run Checkstyle
          command: |
            mvn checkstyle:checkstyle
            if grep -q "<error " target/checkstyle-result.xml; then
              echo "Checkstyle Failed" > checkstyle-status.txt
            else
              echo "Checkstyle Passed" > checkstyle-status.txt
            fi
      - run:
          name: Generate Checkstyle Badge
          command: |
            CHECKSTYLE_STATUS=$(cat checkstyle-status.txt)
            if [ "$CHECKSTYLE_STATUS" = "Checkstyle Passed" ]; then
              curl -o checkstyle-badge.svg https://img.shields.io/badge/checkstyle-passed-brightgreen.svg
            else
              curl -o checkstyle-badge.svg https://img.shields.io/badge/checkstyle-failed-red.svg
            fi
      - store_artifacts:
          path: checkstyle-badge.svg  # Save the badge as an artifact

  javadoc:
    docker:
      - image: cimg/openjdk:11.0  # Java environment
    steps:
      - checkout  # Checkout the repository
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Disable jekyll builds
          command: touch target/site/apidocs/.nojekyll
      - run:
          name: Configure Git for Deployment
          command: |
            git config user.email "rossmamoun8@gmail.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "SHA256:/2v6XWA52PnOi71o4FsNszsTv1X9OI9m9qluah6YpWQ"
      - run:
          name: Deploy Javadoc to gh-pages branch
          command: |
            git checkout -B gh-pages
            git add -f target/site/apidocs/**
            git commit -m "Deploy Javadoc to gh-pages"
            git push origin gh-pages --force

workflows:
  sample:
    jobs:
      - build-and-test  # Running build-and-test job defined above
      - checkstyle:
          requires:
            - build-and-test  # Only run Checkstyle after build and test complete
      - javadoc:
          requires:
            - build-and-test  # Only run Javadoc generation after build and test complete