version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1  # Using Codecov orb for CircleCI

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  # Java environment
    steps:
      - checkout  # Checkout the repository

      # Run Maven build and tests, including generating JaCoCo coverage report
      - run:
          name: Build with Tests
          command: mvn clean package

      # Generate coverage report using JaCoCo
      - run:
          name: Generate Coverage Report
          command: mvn test jacoco:report

      #run Checkstyle to analyze code quality  
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

      # Upload to Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml  # This is where JaCoCo stores the coverage report

workflows:
  sample:
    jobs:
      - build-and-test  # Running build-and-test job defined above
#test